version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  run-test-battery:
    executor:
      name: python/default
      tag: 3.10.11
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry run pytest

workflows:
  tests:
    jobs:
      - run-test-battery
