version: 2.1

orbs:
  python: circleci/python@2.1.0
  snyk: snyk/snyk@1.2.3

jobs:
  snyk-scan:
    executor:
      name: python/default
      tag: 3.10.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - snyk/scan:
          project: '${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}'
  run-test-battery:
    executor:
      name: python/default
      tag: 3.10.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry run python3 -m unittest discover tests

workflows:
  tests:
    jobs:
      - run-test-battery
      - snyk-scan:
          filters:
            branches:
              only:
                - master
